### ISSUE TITLE
VolumeId given null

### ISSUE THREAD

**Issue by Michael-Reich** [bymayo/craft-pdf-transform#10]
```
  {% for item in entry.attachment %}
    {% if item.extension == 'pdf' %}
      {{ craft.pdfTransform.url(item) }}
    {% endif %}
  {% endfor %}
```

Generated this error:

```
TypeError
Argument 1 passed to craft\services\Volumes::getVolumeById() must be of the type int, null given, called in /Users/myname/Source/lions-club-erding/vendor/bymayo/pdf-transform/src/services/PdfTransformService.php on line 59
```

**Comment by Michael-Reich** [comment]
Solved it, the wrong volume was selected in the settings, it needs to be the same as the image. Is this maybe a bug?

**Comment by bymayo** [comment]
@Michael-Reich Where is your PDF file sitting, is it in the same volume?

**Comment by adrianjean** [comment]
I had the same error. 
I had configured my asset field to save in a sub-folder of a volume.

To solve it, I had to create a specific volume for PDFs then set the asset field to save PDF's in that volume, but not in a subfolder.

Make sure to:
- Set that volume in this plugin's settings
- Set that same volume in the asset field settings

**Comment by bymayo** [comment]
@laurabennett @adrianjean I think this error is mainly due to not selecting the volume to save the transformed images into. Just make sure this setting is added.
