### ISSUE TITLE
PHP 8.0 compatibility?

### ISSUE THREAD

**Issue by mierla** [bymayo/craft-pdf-transform#12]
Love this plugin, but running into a problem trying to push it up to live on Fortrabbit.
 
The dependency spatie/pdf-to-image ^1,8,2 doesn't support PHP 8.0.

spatie/pdf-to-image 2.1.0 does.

How can I update the requirement in this plugin's composer.json to fetch the version my host can use?

**Comment by bymayo** [comment]
@mierla The plugins not been updated to use PHP 8 just yet, but I'll look at sorting this.

Thanks

**Comment by mierla** [comment]
Awesome - thanks for looking into it!

**Comment by mmikhalko** [comment]
Looking forward to this as well! Thanks

**Comment by bymayo** [comment]
I've added PHP 8 support now in 1.0.6

https://github.com/bymayo/craft-pdf-transform/releases/tag/1.0.6

**Comment by mmikhalko** [comment]
When 1.0.6 will be able in packagist.org ?

**Comment by bymayo** [comment]
@mmikhalko That's my bad, I didn't update the version number in composer. Should be good now!
