### ISSUE TITLE
Craft v4 support

### ISSUE THREAD

**Issue by anchovy** [bymayo/craft-pdf-transform#15]
Hi, Is this plugin going to be upgraded to support Craft V4? Any timeline for this?
Thanks in advance.

**Comment by bymayo** [comment]
@anchovy Yeah it will be updated to Craft 4. I've actually done this one already and just running some tests this week. So should be out early next week.

**Comment by bymayo** [comment]
@anchovy This is now available for Craft 4, let me know if you have any issues.
