### ISSUE TITLE
Craft 3 Error: file_get_contents: Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Christopholus** [bymayo/craft-pdf-transform#19]
Upon updating to 1.0.8, we seem to be getting issues both uploading PDFs and rendering them using the new **render** function.

Uploading PDFs to any volume gives the following error
![image](https://user-images.githubusercontent.com/1195612/205174397-b8389b95-dccc-4ef0-893c-9907a118cc43.png)

Rendering a PDF that has been uploaded (despite the previous error) shows the following error
`file_get_contents(/files/brochures/Diversity-and-Inclusion-Policy.pdf): Failed to open stream: No such file or directory`

Rendering a PDF with an already-created transform appears to work correctly.

We did not see these issues with our previous version (1.0.6), but we love the new render function as we're able to pass these images directly through imageOptimize to help page performance (so thanks for that!)

I've checked and our PDF Transform is set to use the same Thumbnails volume as it was previously using. This volume is set up with the **@webroot** keyword to ensure the PDF paths are found correctly. It's almost like the new update is unable to find the PDF despite it living at the path in question.

Any help or guidance here would be much appreciated. We have a site launch scheduled tomorrow and only noticed this lingering issue this morning.

Thanks in advance!

**Comment by bymayo** [comment]
@Christopholus Going to be looking in to this over the next day or so. Apologies if this holds up your site launch as I've only just seen this issue.

**Comment by bymayo** [comment]
@Christopholus It seems that if you hit save on the PDF Transform settings page it will then work. It looks like since I've updated this plugin its now working with Project Config. If the plugin settings havent been set/saved then it can't get the Volume ID from the settings - As they don't exist in project config!

Let me know if this fixes the issue for you.

**Comment by Christopholus** [comment]
Thank you for the response, @bymayo!

I went into the plugin settings and made a few changes (changed the **Image Resolution** and adjusted the **Output Image Volume**) and unfortunately the issue still persists. I then went in and changed the volume back to the original "Thumbnails" volume and saved it, and still seeing the same problem.

I will add that both of these sets of changes appear to have updated the project config file, so it looks like the plugin's settings are indeed taking effect on the YAML files.

Unfortunately still hitting a wall over here :(. Any other ideas? I'm going to try removing the plugin entirely and re-adding it to see if that might prompt a heavier project YAML change/reset. Open to other suggestions if you have any!

Thanks for your continued help,
Chris

**Comment by Christopholus** [comment]
Unfortunately removing the plugin and re-installing again netted the same issue. Initially (before I clicked save again on the plugin's settings page) I received this error:
![error_new](https://user-images.githubusercontent.com/1195612/205683435-ac9ef569-efac-441b-945e-c2b56a551c4d.PNG)

Once I re-saved the plugin's settings, back to the same error:
![error_2](https://user-images.githubusercontent.com/1195612/205683569-7a988a2c-a1fc-4d6c-96b6-01cc74e33e94.PNG)

Looking at the project yaml, not much has changed other than my small tweaked settings:
![image](https://user-images.githubusercontent.com/1195612/205683686-427cf69b-20e1-4484-86fe-7941560c8184.png)

Hopefully any of this is helpful! Please let me know if you have any other ideas as to what is going on.

**Comment by bymayo** [comment]
@Christopholus Thanks for the feedback, i'll do another look at this later on tonight.

The line number it's stating (61) is a reference to it getting the Folder ID for the Volume, so looks like it's still an issue with that. I'll double check to see if there is an issue with you using an alias in the path/url for the volume and see if this pulls up anything.

Can you just confirm which version of Craft your using

**Comment by Christopholus** [comment]
Thank you- we really appreciate it. 

Note: That initial error (61) was only present until I had actually adjusted the plugin settings for the first time after re-installing. The original error is being thrown again once re-saving the plugin's settings.

We are on Craft version 3.7.61

**Comment by bymayo** [comment]
@Christopholus I've just pushed a release that fixes the unreadable errors on upload, but I still don't think it will fix your `file_get_contents` error. This error is coming from getting the Asset file to then create a temporary file before it transforms it. I've tried loads of scenarios (Aliases in asset volumes, env vars in asset volumes, file not being in the uploads folder etc) but I can't replicate this error at all. It might be good if you send over a DB dump to me and I can test this with your setup if this is okay? 

Can you also confirm which PHP version you're using? 

Also, note that there is now a new "Transform PDFs on upload" setting that you'll need to switch on (Or keep it off if you don't want this to automatically transform)

Update: Can you also confirm that your files volume has a `Base URL` and that `Assets in this volume have public URLs`?

**Comment by Christopholus** [comment]
@bymayo I think you nailed it! Funny enough, it was your update about the "Base URL" got me thinking. These asset volumes do have base URLs, but they're just set up like so:
![image](https://user-images.githubusercontent.com/1195612/205754282-be88c03a-09b5-42ef-bd9e-0d51e613d199.png)

I wondered if maybe prepending @webroot to the base URL might fix the problem. Aaaaaaand just tried this locally and it works! 🙌 🙌🙌

Darn - I can't believe this was the issue. We haven't had any problems with the Base URLs up until now - so I never would have thought to check here. It is odd that the new update would have been more strict about this. Admittedly my PHP knowledge isn't advanced, but I wonder if the `file_get_contents()` function may have stricter requirements than the way the PDFs were previously referenced?

In either scenario, thank you again for all of the testing you did. You've been a huge help!

**Comment by bymayo** [comment]
@Christopholus Wahoo! So the thing here is that the `file_get_contents()` function I'm using in 1.0.8 onwards requires https in the URL to get the image.

The difference between 1.0.7 and 1.0.8 is that I'm now no longer just looking for a file "path", but actually getting the asset via the URL instead (Mainly to fix people using remote asset storage like Amazon S3 where paths aren't available) so this will explain why it worked previously.

I may need to change this slightly in future as it kind of restricts people using this plugin if they want their assets to be private for instance.

I'd probably advise to use `@web` over `@webroot` for your base URL setting as well. Or even better, setting them as .env vars

**Comment by Christopholus** [comment]
Ah yes that totally makes sense - better as a catch-all for cases where the assets may not be hosted locally.

Thank you for the `@web` tip - we'll work that into our projects! Onwards and upwards 😄
