### ISSUE TITLE
ImageMagick Security Policy Blocking PDF Processing

### ISSUE THREAD

**Issue by klick** [bymayo/craft-pdf-transform#27]
I’m unable to render JPGs from my PDFs on my remote server due to Imagemagicks security policy.

### Environment
- Craft CMS Version:  5.4.10
- PDF Transform Plugin Version: 5.0.1
- PHP Version: 8.2
- Server Environment: managed vServer

### Problem Description
When attempting to process PDFs, the plugin encounters an ImageMagick security policy error:

`attempt to perform an operation not allowed by the security policy 'PDF' @ error/constitute.c/IsCoderAuthorized/426`

### Specific Constraints
- Cannot modify `policy.xml`
- No root/sudo access
- Need a configuration-level solution

### Requested Feature/Fix
- Add configuration option to bypass/modify ImageMagick PDF processing restrictions
- Implement alternative PDF processing method
- Provide configuration for custom PDF processing libraries

### Proposed Solutions
1. Allow custom ImageMagick configuration via plugin settings
2. Add fallback to alternative PDF processing (Ghostscript/other libraries)
3. Provide option to skip/modify security policy check

Would appreciate guidance or a potential configuration approach.

Created with help from claude.ai

**Comment by bymayo** [comment]
@klick I'll take a look at this.

What version of ImageMagick and Ghostscript are you using?

**Comment by klick** [comment]
Ghostscript → 9.53.3
ImageMagick → 6.x

In the meantime my hosting company resolved this for me by making changes to the policymap.xml of ImageMagick. I couldn’t since I have no root privileges on that server (managed vServer).

**Comment by bymayo** [comment]
@klick I'm going to mark this as an enhancement, not a bug as it doesn't seem a bug with this plugin, but a restriction with your build of ImageMagick.

The ideas you put in though are good, to maybe have a different option other than ImageMagick and maybe to add custom ImageMagick configs.
