### ISSUE TITLE
need help to install ghostscript

### ISSUE THREAD

**Issue by hooman-pro** [bymayo/craft-pdf-transform#3]
when i use your library and installed imagick
before install ghostscript i get this error:
PDFDelegateFailed `The system cannot find the file specified. ' @ error/pdf.c/ReadPDFImage/794f
but when i install ghostscript 64 bit chorome says:
This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET
!!!!
I use windows 10 and xampp apache. after install gostscript

in your ducument there is part " Issues regarding Ghostscript" but it is for nginx
what should i do in apache that have not php-fpm.conf file

from command line or from exec by php this command:
magick -density 1200 c:/a/a.pf c:/a/a.jpg
work currectly . but by imagick class or your library not work and when run url google chorom say : site cant be reachabed .....

**Comment by bymayo** [comment]
@hooman-pro So have you installed GhostScript?

It sounds like you need to get this to install correctly before solving any issues with nginx/Apache.

**Comment by bymayo** [comment]
Closing due to no response.
