### ISSUE TITLE
How to apply a transform?

### ISSUE THREAD

**Issue by zenbug** [bymayo/craft-pdf-transform#5]
Can you provide an example of how one would apply a standard Craft transform to the generated image in a template?

**Comment by bymayo** [comment]
Sure! 

```
{# Get the PDF #}
{% set pdf = entry.pdf.one() %}

{# Convert PDF to Image #}
{% set pdfImage = craft.pdfTransform.url(pdf) %}

{# Set Transform #}
{% set pdfImageTransform = {
    mode: 'crop',
    width: 800,
    height: 600
} %}

{# Output Transformed PDF Image #}
<img src="{{ pdfImage.getUrl(pdfImageTransform) }}" alt="PDF">
```

I personally would do this with Imager X plugin though, as you have more control over the caching of the files etc. As I would 100% recommend images are cached if they are transformed.

**Comment by zenbug** [comment]
When I try this code, I get the error "Impossible to invoke a method ("getUrl") on a string variable."

This seems to make sense to me, because the plugin outputs a URL already, right? So I can't use ".getUrl" on something that's already a URL.

Or am I misunderstanding something? Are you able to make that code work?

**Comment by Christopholus** [comment]
We had a similar issue with the getUrl returning an issue (as it's a plain text string, per your comment)

Our team came up with a solution that works well, albeit a bit of a hacky one:

We took PDFTransform's returned URL, trimmed out the folder and ran a craft query to locate the created image asset. We're then able to reference this asset like we would any other, and lean on Craft's excellent transforming abilities to do the rest.

Our solution is below, hope it helps!

`
        {% set resourceThumb = craft.pdfTransform.url(download) %}
        {% set cleanedURL = resourceThumb | trim('/images/resource_thumbs/') %}
        {% set thumbAsset = craft.assets().filename('*'~cleanedURL~'*').one()  %}
        {% if thumbAsset|length %}
            <img src="{{ thumbAsset.getUrl('resourceThumb') }}" alt="" />
        {% endif %}
`

**Comment by zenbug** [comment]
That's clever. Thanks!

**Comment by bymayo** [comment]
You shouldn't need to do this now as of 1.0.8 (Craft 3) and 2.0.1 (Craft 4) as it will now output the Asset, not just the URL if you use the new `render()` method:

```
{% set pdfFile = entry.pdfFile.one() %}

{% set pdfToImage = craft.pdfTransform.render(pdfFile) %}

{% set pdfTransform =  pdfToImage.one().getUrl('resourceThumb') %} 

{% if pdfTransform|length %}
         <img src="{{ pdfTransform.getUrl('resourceThumb') }}" alt="{{ pdfToImage.one().title }}" />
{% endif %}
```
